# Generated by Django 4.2.26 on 2025-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='assessments',
        ),
        migrations.AlterModelTable(
            name='batch',
            table='batches',
        ),
        migrations.AlterModelTable(
            name='college',
            table='colleges',
        ),
        migrations.AlterModelTable(
            name='copomapping',
            table='co_po_mapping',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='courseoutcome',
            table='course_outcomes',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollments',
        ),
        migrations.AlterModelTable(
            name='mark',
            table='marks',
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
        migrations.AlterModelTable(
            name='programoutcome',
            table='program_outcomes',
        ),
        migrations.AlterModelTable(
            name='section',
            table='sections',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table='system_settings',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
